name: Publish Python distribution to PyPI and TestPyPI
on:
  release:
    types:
      - created

jobs:
  build-n-publish:
    name: Publish Python distribution to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
